#!/bin/sh

# Use `set -u` to throw errors if we reference null env vars
set -u

# If we see any argument, set things up for local use
if [ $# = 1 ]; then
  volume="-v $(pwd):/app"
  port="-p 4000:4000"
else
  volume=""
  port=""
fi

docker rm -f ldap_client
docker network create ldap
docker build -t ldap_client -f Dockerfile .
docker run $volume $port --name=ldap_client --net="ldap" -tid ldap_client
